### ISSUE TITLE
Integrate transcription correction tool to bmm

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-utils#19]
Utilize current tool for correcting transcription
https://tools.bcc.media/transcription/

**Comment by sifferhans** [comment]
I have a meeting with Søren on thursday where he will walk through the UX / user-flow.
Saving transcriptions is dependent on an endpoint in the BMM api

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bmm-web/pull/498

**Comment by sifferhans** [comment]
@kkuepper Can this be marked as done now? Or should we wait until we get some feedback from users?
